[package]
name = "portfolio"
version = "0.1.0"
authors = ["Mustapha <mostafaanawawi@gmail.com>"]
edition = "2024"

[dependencies]
dioxus = { version = "0.7.0-rc.0", features = ["router"] }

[features]
default = ["web"]
web = ["dioxus/web"]
